version: '3.8'

services:
  db:
    restart: always
    build:
      context: postgresql
      dockerfile: Dockerfile
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: choran
      POSTGRES_DB: rubybbddd-db
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: infra/Dockerfile
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx:/etc/nginx/default.conf
    depends_on:
      - web

volumes:
  mysqldata: