version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: infra/Dockerfile
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: rubybbddd-db
      MYSQL_USER: choran
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx:/etc/nginx/default.conf
    depends_on:
      - web

volumes:
  db_data: