development:
  private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEAlX1eTG/YqYZPCycz4fCnmi2yxjUzIpcpnV+P6Y1AKo+Ly9HC
    7yOLV+8jtzlhpDij1XIHuONBWpLhvueC2MJEnx2+d5K0+5ASWoNLHjHpT0kLK9tZ
    PCMZ8EOWFulE16q3tbfPqXSITNDas+N/WI89UrLMY/3Y2Yhci4thsmyS60VBFPEl
    Lw7qsTGUEN41MjNd9EI7OlcO5t/0Jfxzgffv79S+I58BKGYLJnWaWS1xskb0TzGC
    TmCJfi1nXbyvExYZyVI2ntEEAA1wXHw0AQ1TquoYh1fJlLN7q4TrnRNsm6bNdBBN
    NMv1bVsekHqoX0xRI0loNdvxyeAu/CO6PxtwAQIDAQABAoIBAAGzUuLItOy8v+Jv
    GDp+O9HXqjxx93pxwMHvB9qOxkeVqW/wm2iP/XJLIJthdjhhgo+Xg/n479HhcNr0
    lDr1/sTWmEeQ7ikcavEHpE+cHrzNpmhhzuKNvapLgoYRMjzHzt4s0JprXm+NQqeg
    M18lBfwOV5/dj91tnSvjMoHOlV9CvnWMiVHQP9Sp5isa1TpK5FScFtPXzv2Wyywl
    BiESoFvdbukdsaVwDWI50XqC9opwKeKTx9s+7rVH1nnSHQ9MQ1V3oNcJtfyUI2/a
    inPhgUpIhfCyQd4slgDSHbQk1ooIyMH5YKDwx6E2B5KB9tpeoeK8acKSJfzY5pG6
    Ui0n/aECgYEAzXFqux1Yu6ovgVBTfWGpTdYcBW7ZLloqL9oewvr1JvPfDQGVJkVa
    51xd9/vEm14D42weMBHWIi8iWXKYWYhGlOdYmd1HfYNHbNt1SQxdAsqk2t3Yn+SR
    pe7wHlUdoXMdXc+BtDlD32CacZrNdpozkSMM5uhSLrY/ybgeiOCD7dkCgYEAukb7
    YpDqVHy2lZVyDRrXzKPtvlEyYz8BZTKPIUyL0pop9v8l7FrR2rkGZPSxylgkDK7+
    kZVhYkGikxnQEnBuHyi6JpJNmD6Th4qmUahMVGH3NrgF7D58Fiet3HkNFNwxQV4d
    agAG8isWmTOlhBHZpkqmcYMjlRA7H4M+DrHOsmkCgYBhrRXYpshEWVLCwaUgTKmJ
    J04lSyGZByddnu/XNigOgA5BicoW6wygSWsn9xzv3ZAttX7YzfIoSI6lRnWmw8MD
    EscuSGWwCBWSbPjjZSxnol8k7CsNQkf5Q5QIZ+FxnGCO9JSvUjax4qUrdDVRuVjh
    HXAJ7NT9/opvZsmlvFEdaQKBgGuiym2JCS5qpeJHaZCy+xFPg/fd2TzJ0leUYGpA
    XecCl88WXeZ2EB7PnSdG0Vj3l1UQ5R5gb9Yj0PopBzcwaiFtGithjJ61QfAnKLW0
    hu6XcQ7YROveqzruEKN9+xYbqgZ4iIyQmXLjfPpngnOPEPHq3sRmn2/p4g/yeTBq
    g+JJAoGBAKbW71bz/j9lSopF/V0LMeu4piuajxWsaCNzd5rXkrZfB6A5MCJrPf9i
    sTTp+WPkksNFINf6xJyHJasMsFpNID2vJK4uD2I6Kb7spAxGoae5NrnpEDKGcOnz
    XEH/oao6xcY33XT/4cIls6TDaKc917Jw20iUV0eB6dtAtDb7HDqP
    -----END RSA PRIVATE KEY-----
  public_key: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlX1eTG/YqYZPCycz4fCn
    mi2yxjUzIpcpnV+P6Y1AKo+Ly9HC7yOLV+8jtzlhpDij1XIHuONBWpLhvueC2MJE
    nx2+d5K0+5ASWoNLHjHpT0kLK9tZPCMZ8EOWFulE16q3tbfPqXSITNDas+N/WI89
    UrLMY/3Y2Yhci4thsmyS60VBFPElLw7qsTGUEN41MjNd9EI7OlcO5t/0Jfxzgffv
    79S+I58BKGYLJnWaWS1xskb0TzGCTmCJfi1nXbyvExYZyVI2ntEEAA1wXHw0AQ1T
    quoYh1fJlLN7q4TrnRNsm6bNdBBNNMv1bVsekHqoX0xRI0loNdvxyeAu/CO6Pxtw
    AQIDAQAB
    -----END PUBLIC KEY-----

production:
  private_key:
  public_key: